version:
  name: velociraptor
  version: 0.5.1
  commit: b8ca2841
  build_time: "2020-10-27T17:37:11+10:00"
Client:
  server_urls:
  - https://192.168.1.106:8000/
  ca_certificate: |
    -----BEGIN CERTIFICATE-----
    MIIDKjCCAhKgAwIBAgIQAJUwFf9SEX6h5RbBWer+TTANBgkqhkiG9w0BAQsFADAa
    MRgwFgYDVQQKEw9WZWxvY2lyYXB0b3IgQ0EwHhcNMjAxMDI3MTUzNjI3WhcNMzAx
    MDI1MTUzNjI3WjAaMRgwFgYDVQQKEw9WZWxvY2lyYXB0b3IgQ0EwggEiMA0GCSqG
    SIb3DQEBAQUAA4IBDwAwggEKAoIBAQDJ4V3Jx4s43ETMgdhijz0hRHWrTz+XtRCk
    ny2ZnHOHV9kYszhoETui4HjYfPLkkDsVciF0SH1rJG+I25YzvirWib8CjrBWwKac
    65abj1ierZmI6xICFqhkf9wGPiZ3wealRN6n8T0+yqwbskpNkSLZbfZmUl2zY9kD
    Po+lyOm3mm0RX2apIp6BbZDqWS+BnACM0Ao2GolFUrZbvqUtu7Gn2OJocCDCpMVN
    cABTsJClbRhsKdgTKlpvLzI/V2RODmNdD2ys16bEIblISsppj/VYaipLIsSruvWW
    Iw8BX2984/0bsNQAiQ3EGnoC/wmMo6kqEP45nNUKV/HAxUEmQ8yZAgMBAAGjbDBq
    MA4GA1UdDwEB/wQEAwICpDAdBgNVHSUEFjAUBggrBgEFBQcDAQYIKwYBBQUHAwIw
    DwYDVR0TAQH/BAUwAwEB/zAoBgNVHREEITAfgh1WZWxvY2lyYXB0b3JfY2EudmVs
    b2NpZGV4LmNvbTANBgkqhkiG9w0BAQsFAAOCAQEAxpltLoEsC3f/68EaDSgAFvzT
    Pvw8Q+Q3vPCshLLPkK3h9j7WK97MM7KezHppve5i8eTxR+9pQymLUi/vUgGCoRAH
    i5xtQNlRSvzvuL/mFJWCA7spypetabvqSvQt7xOKr2cWBs54ugCou+D2H9I1ZUId
    Ps3F0ap9UesA6Kq89TCml7SFWxJOYWjmqBURANsBhc4hoW5zh9pKgd+mUMx29Odk
    955xEqaA0UYIrEl7xn0iPfeped0jkWDjDXuvlgLtAuqjFL0HDNiP/OxR7kG2Iant
    kriL3rgtqtwkEQ4U9X1GaMG25pW6pPtNdS/hJ+//BGWr4sLUI7a01XV4SG4pdA==
    -----END CERTIFICATE-----
  nonce: 8jx6YcCY0r8=
  writeback_darwin: /etc/velociraptor.writeback.yaml
  writeback_linux: /etc/velociraptor.writeback.yaml
  writeback_windows: velociraptor.writeback.yaml
  tempdir_windows: $ProgramFiles\Velociraptor\Tools
  max_poll: 60
  windows_installer:
    service_name: Velociraptor
    install_path: $ProgramFiles\Velociraptor\Velociraptor.exe
    service_description: Velociraptor service
  darwin_installer:
    service_name: com.velocidex.velociraptor
    install_path: /usr/local/sbin/velociraptor
  version:
    name: velociraptor
    version: 0.5.1
    commit: b8ca2841
    build_time: "2020-10-27T17:37:11+10:00"
  use_self_signed_ssl: true
  pinned_server_name: VelociraptorServer
  max_upload_size: 5242880
  local_buffer:
    memory_size: 52428800
    disk_size: 1073741824
    filename_linux: /var/tmp/Velociraptor_Buffer.bin
    filename_windows: $TEMP/Velociraptor_Buffer.bin
    filename_darwin: /var/tmp/Velociraptor_Buffer.bin
